if(EXISTS "/root/miniob2/Miniob-Solution-2023-main/build_debug/unittest/log_test[1]_tests.cmake")
  include("/root/miniob2/Miniob-Solution-2023-main/build_debug/unittest/log_test[1]_tests.cmake")
else()
  add_test(log_test_NOT_BUILT log_test_NOT_BUILT)
endif()
